server:
  port: 9010
spring:
  rabbitmq:
    host: hwyee.cn
    username: admin
    password: admin
  application:
    name: spring-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 123.249.36.245:8848
        ip: 123.249.36.245
