async:
  pool:
    core-size: 5
    max-size: 50
    keep-alive: 60
    queue-capacity: 100
logging:
  level:
    cn.hwyee: debug
snowflake:
  max-vibration-offset: 4000
  worker-id: 1023
  max-tolerate-time-difference-milliseconds: 30
zookeeper:
  connect-string: "hwyee.cn:2183"